name: PublicDNS

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0 
    - name: Validator
      run: |
        sudo apt install -y gcc make
        pip3 install -r requirements.txt
        sudo make massdns dnsvalidator
        python3 -c "from lazydns import fetch_resolvers; fetch_resolvers()" > tmp.txt
        python3 -c "from lazydns import gen_nxdomain; gen_nxdomain(25000, 'google.com'); gen_nxdomain(25000, 'youtube.com')" > nx_check.txt
        rm resolvers.txt
        dnsvalidator -tL tmp.txt -threads 10 -timeout 500 -o resolvers.txt
        sed -i '/^$/d' resolvers.txt
        bin/massdns -q -r resolvers.txt --predictable -s 150 -o J -w nx_check.json nx_check.txt
        cat nx_check.json | grep NOERROR | jq -r '.resolver' | awk -F ":" '{print $1}' | sort -u > bad_resolvers.txt
        for resolver in $(cat bad_resolvers.txt); do sed -i "/${resolver}/d" resolvers.txt; done
        sort -u -V resolvers.txt -o resolvers.txt
        rm tmp.txt
        rm nx_check.txt
        rm nx_check.json
        rm bad_resolvers.txt
    - name: Commit resolvers
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update resolvers" -a
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
